from .variants import ALL_AXES, ALL_COMPONENTS, MORPH_ONLY_AXES, Variant, make_family

VARIANTS: dict[str, Variant] = {
    "mpa": Variant(
        namespace="mpa",
        label="Pure MPA",
        group="mpa",
        views_module="mpa.views",
        url_prefix="mpa/",
        app_name="mpa",
        source_url="https://github.com/lucas-rollin/django-htmx-nav/blob/main/example/mpa/views.py",
        uses_htmx=False,
        family="mpa",
        family_label="Pure MPA",
        family_description="Standard Multi-Page Application performing full page reloads on every navigation.",
    ),
    **make_family(
        key="vanilla_htmx_unaware_views",
        label="Vanilla HTMX unaware views",
        description="HTMX-unaware views with templates wrapped in hx-boost, returning full HTML shells on partial requests.",
        group="vanilla",
        views_module="mpa.views",
        url_prefix="htmx/",
        app_name="mpa",
        source_url="https://github.com/lucas-rollin/django-htmx-nav/blob/main/example/mpa/views.py",
        axes=ALL_AXES,
    ),
    **make_family(
        key="vanilla_htmx_composite",
        label="Vanilla HTMX Composite OOB",
        description="Manual out-of-band (OOB) swaps in Python views for coarse navigation components (sidebar and breadcrumbs).",
        group="vanilla",
        views_module="vanilla_htmx_composite.views",
        url_prefix="vanilla-htmx/composite/",
        app_name="vanilla_htmx_composite",
        source_url="https://github.com/lucas-rollin/django-htmx-nav/tree/main/example/vanilla_htmx_composite",
        component_swaps=["sidebar", "breadcrumbs"],
        axes=ALL_AXES,
    ),
    **make_family(
        key="vanilla_htmx_atomic",
        label="Vanilla HTMX Atomic OOB",
        description="Manual out-of-band (OOB) swaps for all navigation components, requiring conditional template rendering.",
        group="vanilla",
        views_module="vanilla_htmx_atomic.views",
        url_prefix="vanilla-htmx/atomic/",
        app_name="vanilla_htmx_atomic",
        source_url="https://github.com/lucas-rollin/django-htmx-nav/tree/main/example/vanilla_htmx_atomic",
        component_swaps=list(ALL_COMPONENTS),
        axes=MORPH_ONLY_AXES,
    ),
    **make_family(
        key="htmx_nav_baseline",
        label="HTMX Nav Baseline",
        description="Basic django-htmx-nav implementation using render_shell with static OOB swaps and default partials.",
        group="package",
        views_module="htmx_nav_demo.views_baseline",
        url_prefix="htmx-nav/baseline/",
        app_name="htmx_nav_demo",
        source_url="https://github.com/lucas-rollin/django-htmx-nav/blob/main/example/htmx_nav_demo/views_baseline.py",
        component_swaps=["sidebar", "breadcrumbs"],
        uses_htmx_nav=True,
        axes=ALL_AXES,
    ),
    **make_family(
        key="htmx_nav_composite",
        label="HTMX Nav Composite",
        description="Uses render_nav to dynamically attach OOB swaps for sidebar and breadcrumbs.",
        group="package",
        views_module="htmx_nav_demo.views_composite",
        url_prefix="htmx-nav/composite/",
        app_name="htmx_nav_demo",
        source_url="https://github.com/lucas-rollin/django-htmx-nav/blob/main/example/htmx_nav_demo/views_composite.py",
        component_swaps=["sidebar", "breadcrumbs"],
        uses_htmx_nav=True,
        axes=ALL_AXES,
    ),
    **make_family(
        key="htmx_nav_atomic",
        label="HTMX Nav Atomic",
        description="Uses render_nav to target all individual navigation components for precise OOB updates.",
        group="package",
        views_module="htmx_nav_demo.views_atomic",
        url_prefix="htmx-nav/atomic/",
        app_name="htmx_nav_demo",
        source_url="https://github.com/lucas-rollin/django-htmx-nav/blob/main/example/htmx_nav_demo/views_atomic.py",
        component_swaps=list(ALL_COMPONENTS),
        uses_htmx_nav=True,
        axes=MORPH_ONLY_AXES,
    ),
    **make_family(
        key="htmx_nav_declarative",
        label="HTMX Nav Declarative",
        description="Declarative navigation registry system that automatically handles render_shell, keeping views thin.",
        group="package",
        views_module="htmx_nav_demo.views_declarative",
        url_prefix="htmx-nav/declarative/",
        app_name="htmx_nav_demo",
        source_url="https://github.com/lucas-rollin/django-htmx-nav/blob/main/example/htmx_nav_demo/views_declarative.py",
        component_swaps=list(ALL_COMPONENTS),
        uses_htmx_nav=True,
        axes=MORPH_ONLY_AXES,
    ),
}
