from .variants import Variant

VARIANTS = {
    "mpa": Variant(
        namespace="mpa",
        label="Pure MPA",
        group="mpa",
        views_module="mpa.views",
        url_prefix="mpa/",
        app_name="mpa",
    ),
    "pure_hx_boost": Variant(
        namespace="pure_hx_boost",
        label="HX-Boost (unaware views)",
        group="vanilla",
        views_module="mpa.views",
        url_prefix="hx-boost/",
        app_name="mpa",
        uses_htmx=True,
    ),
    "pure_hx_select": Variant(
        namespace="pure_hx_select",
        label="HX-Select (client-side fragment)",
        group="vanilla",
        views_module="mpa.views",
        url_prefix="hx-select/",
        app_name="mpa",
        uses_htmx=True,
        uses_hx_select=True,
    ),
    "vanilla_htmx_composite": Variant(
        namespace="vanilla_htmx_composite",
        label="Vanilla HTMX (composite)",
        group="vanilla",
        views_module="vanilla_htmx_composite.views",
        url_prefix="vanilla-htmx/composite/",
        app_name="vanilla_htmx_composite",
        component_swaps=["sidebar", "breadcrumbs"],
        uses_htmx=True,
    ),
    "vanilla_htmx_atomic": Variant(
        namespace="vanilla_htmx_atomic",
        label="Vanilla HTMX (atomic)",
        group="vanilla",
        views_module="vanilla_htmx_atomic.views",
        url_prefix="vanilla-htmx/atomic/",
        app_name="vanilla_htmx_atomic",
        component_swaps=["sidebar", "breadcrumbs", "tabs", "subtabs", "steps"],
        uses_htmx=True,
    ),
    "htmx_nav_baseline": Variant(
        namespace="htmx_nav_baseline",
        label="HTMX Nav Baseline",
        group="package",
        views_module="htmx_nav_demo.views_baseline",
        url_prefix="htmx-nav/baseline/",
        app_name="htmx_nav_demo",
        component_swaps=["sidebar", "breadcrumbs"],
        uses_htmx=True,
        uses_htmx_nav=True,
    ),
    "htmx_nav_composite": Variant(
        namespace="htmx_nav_composite",
        label="HTMX Nav Composite",
        group="package",
        views_module="htmx_nav_demo.views_composite",
        url_prefix="htmx-nav/composite/",
        app_name="htmx_nav_demo",
        component_swaps=["sidebar", "breadcrumbs"],
        uses_htmx=True,
        uses_htmx_nav=True,
    ),
    "htmx_nav_atomic": Variant(
        namespace="htmx_nav_atomic",
        label="HTMX Nav Atomic",
        group="package",
        views_module="htmx_nav_demo.views_atomic",
        url_prefix="htmx-nav/atomic/",
        app_name="htmx_nav_demo",
        component_swaps=["sidebar", "breadcrumbs", "tabs", "subtabs", "steps"],
        uses_htmx=True,
        uses_htmx_nav=True,
    ),
    "htmx_nav_declarative": Variant(
        namespace="htmx_nav_declarative",
        label="HTMX Nav Declarative",
        group="package",
        views_module="htmx_nav_demo.views_declarative",
        url_prefix="htmx-nav/declarative/",
        app_name="htmx_nav_demo",
        component_swaps=["sidebar", "breadcrumbs", "tabs", "subtabs", "steps"],
        uses_htmx=True,
        uses_htmx_nav=True,
    ),
}
