site_name: django-htmx-nav
site_url: https://lucas-rollin.github.io/django-htmx-nav/
site_description: Documentation for Django HTMX package.

theme:
  name: material
  palette:
    # Light/Dark mode switcher
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.copy
    - navigation.expand
    - navigation.sections

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition

nav:
  - Home: index.md
  - Quickstart: quickstart.md
  - Docstrings: api.md
  - pattern:
      - Context Processor & Template Tags: pattern/context_processor_and_templatetags.md
      - Centralized Navigation Registry: pattern/registry_pattern.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]